CREATE DATABASE remote_gs;
USE remote_gs;

CREATE TABLE CLIENT(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CLIENT_TYPE INT,
	CLIENT_HASH TEXT,
	CLIENT_NAME TEXT DEFAULT NULL,
	CLIENT_PASSWORD TEXT DEFAULT NULL,
	CLIENT_ACTIVATED INT DEFAULT 1,
	CLIENT_CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)Engine = innoDB CHARACTER SET utf8 COLLATE utf8_general_ci AUTO_INCREMENT=8563;

CREATE TABLE EVENT_LOG(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CLIENT_ID INT,
	EVENT_TYPE TEXT,
	EVENT_DESC TEXT,
	EVENT_CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)Engine = innoDB CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE INDEX EVENT_LOG_CLIENT_ID_INDEX ON EVENT_LOG (CLIENT_ID);

CREATE TABLE CLIENT_PAIRING(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	REMOTE_ID INT,
	GROOVESHARK_ID INT,
	FOREIGN KEY (REMOTE_ID) REFERENCES CLIENT(ID) ON DELETE CASCADE,
	FOREIGN KEY (GROOVESHARK_ID) REFERENCES CLIENT(ID) ON DELETE CASCADE
)Engine = innoDB CHARACTER SET utf8 COLLATE utf8_general_ci;